/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Auction = IDL.Record({
  'month' : IDL.Nat,
  'winner' : IDL.Principal,
  'bidAmount' : IDL.Nat,
  'closedAt' : Time,
  'groupId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'member' : IDL.Null,
  'organiser' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const ChitGroup = IDL.Record({
  'id' : IDL.Text,
  'organiser' : IDL.Principal,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'capacity' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Payment = IDL.Record({
  'month' : IDL.Nat,
  'user' : IDL.Principal,
  'groupId' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'closeAuction' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Principal, IDL.Nat],
      [],
      [],
    ),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getAuctionHistoryForGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Auction)],
      ['query'],
    ),
  'getAuctionHistoryForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Auction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(ChitGroup)], ['query']),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserGroups' : IDL.Func([], [IDL.Vec(ChitGroup)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfile_deprecated' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'makePayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Auction = IDL.Record({
    'month' : IDL.Nat,
    'winner' : IDL.Principal,
    'bidAmount' : IDL.Nat,
    'closedAt' : Time,
    'groupId' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'member' : IDL.Null, 'organiser' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const ChitGroup = IDL.Record({
    'id' : IDL.Text,
    'organiser' : IDL.Principal,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'capacity' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'month' : IDL.Nat,
    'user' : IDL.Principal,
    'groupId' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'closeAuction' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Principal, IDL.Nat],
        [],
        [],
      ),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getAuctionHistoryForGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Auction)],
        ['query'],
      ),
    'getAuctionHistoryForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Auction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(ChitGroup)], ['query']),
    'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserGroups' : IDL.Func([], [IDL.Vec(ChitGroup)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile_deprecated' : IDL.Func(
        [],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'makePayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };