/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Auction {
  'month' : bigint,
  'winner' : Principal,
  'bidAmount' : bigint,
  'closedAt' : Time,
  'groupId' : string,
}
export interface ChitGroup {
  'id' : string,
  'organiser' : Principal,
  'duration' : bigint,
  'name' : string,
  'createdAt' : Time,
  'capacity' : bigint,
  'amount' : bigint,
}
export interface Payment {
  'month' : bigint,
  'user' : Principal,
  'groupId' : string,
  'amount' : bigint,
  'paidAt' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'id' : string,
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'member' : null } |
  { 'organiser' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'closeAuction' : ActorMethod<[string, bigint, Principal, bigint], undefined>,
  'createGroup' : ActorMethod<[string, bigint, bigint, bigint], string>,
  'getAuctionHistoryForGroup' : ActorMethod<[string], Array<Auction>>,
  'getAuctionHistoryForUser' : ActorMethod<[Principal], Array<Auction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getGroup' : ActorMethod<[string], [] | [ChitGroup]>,
  'getGroupMembers' : ActorMethod<[string], Array<UserProfile>>,
  'getPaymentHistory' : ActorMethod<[string], Array<Payment>>,
  'getUserByEmail' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserGroups' : ActorMethod<[], Array<ChitGroup>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile_deprecated' : ActorMethod<[], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'makePayment' : ActorMethod<[string, bigint, bigint], undefined>,
  'registerUser' : ActorMethod<[string, string, UserRole], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];